-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 13:33:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`historiaClinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historiaClinica` (
  `noExpediente` INT NOT NULL,
  `fecha` DATE NULL,
  `folio` VARCHAR(20) NULL,
  `idUsuarioCreador` INT NULL,
  PRIMARY KEY (`noExpediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datosGenerales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datosGenerales` (
  `noExpediente` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `fechaNacimiento` DATE NULL,
  `lugarNacimiento` VARCHAR(45) NULL,
  `edad` INT NULL,
  `sexo` VARCHAR(10) NULL,
  `domicilioCalle` VARCHAR(50) NULL,
  `domicilioMunicipio` VARCHAR(50) NULL,
  `noDomicilio` VARCHAR(10) NULL,
  `domicilioColonia` VARCHAR(30) NULL,
  `domicilioEstado` VARCHAR(20) NULL,
  `datosGeneralescol` VARCHAR(45) NULL,
  `celular` VARCHAR(15) NULL,
  `ocupacion` VARCHAR(20) NULL,
  `fechaUltimacitadental` DATE NULL,
  `motivoConsulta` VARCHAR(100) NULL,
  INDEX `fk_datosGenerales_historiaClinica1_idx` (`noExpediente` ASC) VISIBLE,
  PRIMARY KEY (`noExpediente`),
  CONSTRAINT `fk_datosGenerales_historiaClinica1`
    FOREIGN KEY (`noExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`antecedentesHeredoFamiliares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`antecedentesHeredoFamiliares` (
  `noExpediente` INT NOT NULL,
  `diabetes` INT NULL,
  `fibrosisQuistica` INT NULL,
  `anemiaFalciforme` INT NULL,
  `cancer` INT NULL,
  `hemofilia` INT NULL,
  `hipertencion` INT NULL,
  `hipercolesterolemia` INT NULL,
  INDEX `fk_antecedentesHeredoFamiliares_historiaClinica1_idx` (`noExpediente` ASC) VISIBLE,
  PRIMARY KEY (`noExpediente`),
  CONSTRAINT `fk_antecedentesHeredoFamiliares_historiaClinica1`
    FOREIGN KEY (`noExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`antecedentesPersonalesPatologicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`antecedentesPersonalesPatologicos` (
  `noExpediente` INT NOT NULL,
  `sida` INT NULL,
  `diabetes` INT NULL,
  `prediabetes` INT NULL,
  `carebrovasculares` INT NULL,
  `hepatitis` INT NULL,
  `osteoartritis` INT NULL,
  `osteorporosis` INT NULL,
  `herpes` INT NULL,
  `cardiopatias` INT NULL,
  `cancer` INT NULL,
  PRIMARY KEY (`noExpediente`),
  CONSTRAINT `fk_table1_historiaClinica1`
    FOREIGN KEY (`noExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`antecedentesPersonalesNoPatologicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`antecedentesPersonalesNoPatologicos` (
  `NoExpediente` INT NOT NULL,
  `antecedentesPersonalesNoPatologicoscol1` VARCHAR(45) NULL,
  `adiccionTabaco` INT NULL,
  `adiccionAlcohol` INT NULL,
  `alergias` INT NULL,
  `alergiasCuales` VARCHAR(100) NULL,
  `antecedentesPersonalesNoPatologicoscol` VARCHAR(45) NULL,
  `primeraMestruacion` DATE NULL,
  `embarazo` INT NULL,
  `mesesEmbarazo` INT NULL,
  PRIMARY KEY (`NoExpediente`),
  INDEX `fk_antecedentesPersonalesNoPatologicos_historiaClinica1_idx` (`NoExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_antecedentesPersonalesNoPatologicos_historiaClinica1`
    FOREIGN KEY (`NoExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospitalizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitalizaciones` (
  `NoExpediente` INT NOT NULL,
  `fechaHospitalizacion` DATE NULL,
  `motivo` VARCHAR(50) NULL,
  PRIMARY KEY (`NoExpediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospitalizaciones_has_historiaClinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitalizaciones_has_historiaClinica` (
  `hospitalizacionesNoExpediente` INT NOT NULL,
  `historiaClinicaNoExpediente` INT NOT NULL,
  PRIMARY KEY (`hospitalizacionesNoExpediente`, `historiaClinicaNoExpediente`),
  INDEX `fk_table1_has_historiaClinica_historiaClinica1_idx` (`historiaClinicaNoExpediente` ASC) VISIBLE,
  INDEX `fk_table1_has_historiaClinica_table11_idx` (`hospitalizacionesNoExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_table1_has_historiaClinica_table11`
    FOREIGN KEY (`hospitalizacionesNoExpediente`)
    REFERENCES `mydb`.`hospitalizaciones` (`NoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_has_historiaClinica_historiaClinica1`
    FOREIGN KEY (`historiaClinicaNoExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exporacionFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exporacionFisica` (
  `noExpediente` INT NOT NULL,
  `peso` FLOAT NULL,
  `talla` FLOAT NULL,
  `presionArterial` FLOAT NULL,
  `frecuenciaCardiaca` INT NULL,
  `temperatura` FLOAT NULL,
  `frecuenciaRespiratoria` INT NULL,
  PRIMARY KEY (`noExpediente`),
  INDEX `fk_exporacionFisica_historiaClinica1_idx` (`noExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_exporacionFisica_historiaClinica1`
    FOREIGN KEY (`noExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archivos` (
  `idarchivos` INT NOT NULL AUTO_INCREMENT,
  `nombreArchivo` VARCHAR(45) NULL,
  `nombreArchivoReal` VARCHAR(255) NULL,
  `fechaCreacion` DATE NULL,
  `noExpediente` INT NOT NULL,
  PRIMARY KEY (`idarchivos`, `noExpediente`),
  INDEX `fk_archivos_historiaClinica1_idx` (`noExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_archivos_historiaClinica1`
    FOREIGN KEY (`noExpediente`)
    REFERENCES `mydb`.`historiaClinica` (`noExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `IdUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `correo` VARCHAR(100) NULL,
  `fechaNacimiento` DATE NULL,
  `rol` INT NULL,
  `contrasena` VARCHAR(30) NULL,
  PRIMARY KEY (`IdUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
